language: c
services: PostgreSQL

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - cat /etc/lsb-release
  - curl http://debian.openturns.org/openturns.org-repo.key | sudo apt-key add -
  - sudo add-apt-repository -y "http://ubuntu.openturns.org/dists/precise/main/"
  - sudo apt-get install libopenturns-dev
  
install:
  - if [ "$RCPP" = "release" ]; then ./travis-tool.sh r_binary_install Rcpp; fi
  - if [ "$RCPP" = "devel" ]; then cd ..; git clone https://github.com/RcppCore/Rcpp.git; R CMD INSTALL Rcpp; cd -; fi
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
env:
  - RCPP=release
  - RCPP=devel
